### ISSUE TITLE
No way to change Ore Growth Rate

### ISSUE THREAD

**Issue by rknetwork** [OpenRA/raclassic#203]
Couldn't find anything similar in mods\ra\rules yml files

`GrowthRate=2            ; minutes between ore (Tiberium) growth`

**Comment by MustaphaTR** [comment]
[Here](https://github.com/OpenRA/raclassic/blob/master/mods/raclassic/rules/misc.yaml#L282). You need to add `Interval:` value under it, it is not defined here because it is using the default value, which is `75` (which would be 3 seconds in normal speed).

[Down here](https://github.com/OpenRA/raclassic/blob/master/mods/raclassic/rules/misc.yaml#L303) is the version for Gem Mines, but i don't think Gem Mines are used anywhere in this mod. You would need to apply the same here to for the change to apply them too.
